export DEFAULT_USER=$(whoami)
export CFLAGS="-I/opt/boxen/homebrew/include/ -Wall"
export CXXFLAGS="$CFLAGS"
export LDFLAGS=-L/opt/boxen/homebrew/lib/
export EDITOR=vim
export VISUAL=gvim
export CLICOLOR=1
export HISTFILE=~/.zhistory
export HISTSIZE=100000
export HISTSAVE=100000
